# Generated by Django 5.0.7 on 2024-10-29 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus_table',
            fields=[
                ('bus_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('bus_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobial', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('bus_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bus_table')),
            ],
        ),
    ]
